//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceCallApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service_Customer
    {
        public Service_Customer()
        {
            this.Service_Ticket = new HashSet<Service_Ticket>();
        }
    
        public int Customer_ID { get; set; }
        public string Customer_Name { get; set; }
        public string Company_Name { get; set; }
        public string Phone_No { get; set; }
        public string Email_ID { get; set; }
        public string Address { get; set; }
    
        public virtual ICollection<Service_Ticket> Service_Ticket { get; set; }
    }
}
