//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceCallApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service_Ticket
    {
        public long Ticket_ID { get; set; }
        public int Customer_ID { get; set; }
        public Nullable<int> Assigned_To { get; set; }
        public string Ticket_Type { get; set; }
        public Nullable<System.DateTime> Ticket_Creation_Date { get; set; }
        public string Narration { get; set; }
        public Nullable<System.DateTime> Assigned_Date { get; set; }
        public Nullable<System.DateTime> Call_Attended_Date { get; set; }
        public string Status { get; set; }
        public string Narration_By_Engineer { get; set; }
    
        public virtual Service_Customer Service_Customer { get; set; }
        public virtual Service_Employee Service_Employee { get; set; }
    }
}
