//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceCallApplication.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ServiceCallEntities : DbContext
    {
        public ServiceCallEntities()
            : base("name=ServiceCallEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Service_Activity> Service_Activity { get; set; }
        public DbSet<Service_Company> Service_Company { get; set; }
        public DbSet<Service_Customer> Service_Customer { get; set; }
        public DbSet<Service_Employee> Service_Employee { get; set; }
        public DbSet<Service_Location_Tracking> Service_Location_Tracking { get; set; }
        public DbSet<Service_Ticket> Service_Ticket { get; set; }
        public DbSet<Service_User_Access_Table> Service_User_Access_Table { get; set; }
    }
}
