//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceCallApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service_Location_Tracking
    {
        public long Location_Tracking_ID { get; set; }
        public int User_ID { get; set; }
        public byte[] TimeStamp { get; set; }
        public string Phone_No { get; set; }
        public long Lat { get; set; }
        public long Lon { get; set; }
    
        public virtual Service_Employee Service_Employee { get; set; }
    }
}
