//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceCallApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service_User_Access_Table
    {
        public int Access_ID { get; set; }
        public string User_Type { get; set; }
        public string Details { get; set; }
        public int Add_Ticket { get; set; }
        public int Close_Ticket { get; set; }
        public int Assign_Ticket { get; set; }
        public int Reports { get; set; }
        public int AMC { get; set; }
        public int Employee { get; set; }
        public int Customer { get; set; }
        public int Location_Tracking { get; set; }
    }
}
