//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceCallApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service_Company
    {
        public int Company_id { get; set; }
        public string Company_Name { get; set; }
        public string Address { get; set; }
        public string Email_ID_For_Display { get; set; }
        public byte[] Logo { get; set; }
    }
}
